Added links for youtube, vimeo
drogue-iot/blog.drogue.io pull request #9
Opened 2021-02-04 14:53 UTC by vedangj044

Youtube, Vimeo links in templates/index.html

2021-02-04 16:02 UTC, ctron requested changes
Thanks for thinking about this, and for fixing it!

I found a minor spelling error, added a suggestion.

I also think it would be useful if the Twitter account was added: https://twitter.com/DrogueIoT

2021-02-04 16:02 UTC, ctron commented on templates/index.html
> +	    <li>{{ common::link_list_item(label='Youtube', href='https://www.youtube.com/channel/UC7GZUy2hKidvY6V_3QZfCcA') }}</li>
```suggestion
	    <li>{{ common::link_list_item(label='YouTube', href='https://www.youtube.com/channel/UC7GZUy2hKidvY6V_3QZfCcA') }}</li>
```

2021-02-04 16:13 UTC, vedangj044 commented
sorry for the inconvenience of re-review.

2021-02-05 13:27 UTC, ctron approved these changes
Awesome. Thanks!

2021-02-05 13:27 UTC, merged